### ISSUE TITLE
Check plain root crash

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#113]
Testing for the getting started with 2015 docs (https://github.com/cernopendata/opendata.cern.ch/issues/3165):

In slc6 CMSSW_7_6_7 container, plain root crashes when plotting electron pt from 

root root://eospublic.cern.ch//eos/opendata/cms/Run2015D/DoubleEG/MINIAOD/08Jun2016-v1/10000/00387F48-342F-E611-AB5D-0CC47A4D76AC.root

patElectrons_slimmedElectrons__RECO.obj.m_state.p4Polar_.fCoordinates.fPt

The plotting gets done, but this is quite embarrassing as a first touch....

```
root [2]
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x7feb947ff700 (LWP 432)):
#0  0x00007feba08d0243 in epoll_wait () from /lib64/libc.so.6
#1  0x00007feb95f3bdf7 in XrdSys::IOEvents::PollE::Begin (this=0x355e380, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007feb95f385c5 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffff2513e50) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007feb95f36e18 in XrdSysThread_Xeq (myargs=0x1ed2f20) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysPthread.cc:86
#4  0x00007feb9fd29aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007feba08cfc4d in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7feb93ffe700 (LWP 433)):
#0  0x00007feba0893cbd in nanosleep () from /lib64/libc.so.6
#1  0x00007feb95f375e3 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007feb95e78902 in XrdCl::TaskManager::RunTasks (this=0x2f260b0) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007feb95e78a89 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:37
#4  0x00007feb9fd29aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007feba08cfc4d in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7feb937fd700 (LWP 434)):
#0  0x00007feba08cc499 in syscall () from /lib64/libc.so.6
#1  0x00007feb95ed76c0 in Wait (this=0x3122da0) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  Get (this=0x224f328) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x224f310) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007feb95ed7849 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007feb9fd29aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007feba08cfc4d in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7feb92ffc700 (LWP 435)):
#0  0x00007feba08cc499 in syscall () from /lib64/libc.so.6
#1  0x00007feb95ed76c0 in Wait (this=0x3122da0) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  Get (this=0x224f328) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x224f310) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007feb95ed7849 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007feb9fd29aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007feba08cfc4d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7feb927fb700 (LWP 436)):
#0  0x00007feba08cc499 in syscall () from /lib64/libc.so.6
#1  0x00007feb95ed76c0 in Wait (this=0x3122da0) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  Get (this=0x224f328) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x224f310) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007feb95ed7849 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_7_6_7-slc6_amd64_gcc493/build/CMSSW_7_6_7-build/BUILD/slc6_amd64_gcc493/external/xrootd/4.5.0/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007feb9fd29aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007feba08cfc4d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7feba0f998a0 (LWP 411)):
#0  0x00007feba08938dd in waitpid () from /lib64/libc.so.6
#1  0x00007feba08254e9 in do_system () from /lib64/libc.so.6
#2  0x00007feba0825820 in system () from /lib64/libc.so.6
#3  0x00007feba0e0f06a in TUnixSystem::StackTrace() () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#4  0x00007feba0e1103c in TUnixSystem::DispatchSignals(ESignals) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#5  <signal handler called>
#6  0x00007feb91b19d00 in TVirtualBranchBrowsable::GetCollectionContainedType(TBranch const*, TVirtualBranchBrowsable const*, TClass*&) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#7  0x00007feb91b1beb8 in TMethodBrowsable::GetBrowsables(TList&, TBranch const*, TVirtualBranchBrowsable const*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#8  0x00007feb91b1a294 in TVirtualBranchBrowsable::FillListOfBrowsables(TList&, TBranch const*, TVirtualBranchBrowsable const*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#9  0x00007feb91b1a356 in TVirtualBranchBrowsable::GetLeaves() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#10 0x00007feb91b1ccb9 in TVirtualBranchBrowsable::IsFolder() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#11 0x00007feb91b9c9cf in TMethodBrowsable::GetIconName() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#12 0x00007feb78d596d7 in TGFileBrowser::GetObjPicture(TGPicture const**, TObject*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#13 0x00007feb78d5b1cd in TGFileBrowser::Add(TObject*, char const*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#14 0x00007feba0d3c9e2 in TBrowser::Add(TObject*, char const*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#15 0x00007feba0dbc04f in TCollection::Browse(TBrowser*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#16 0x00007feb91b343e9 in TBranchElement::Browse(TBrowser*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#17 0x00007feb78d5c4dd in TGFileBrowser::DoubleClicked(TGListTreeItem*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#18 0x00007feb9d4b6b27 in ?? ()
#19 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007feb91b19d00 in TVirtualBranchBrowsable::GetCollectionContainedType(TBranch const*, TVirtualBranchBrowsable const*, TClass*&) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#7  0x00007feb91b1beb8 in TMethodBrowsable::GetBrowsables(TList&, TBranch const*, TVirtualBranchBrowsable const*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#8  0x00007feb91b1a294 in TVirtualBranchBrowsable::FillListOfBrowsables(TList&, TBranch const*, TVirtualBranchBrowsable const*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#9  0x00007feb91b1a356 in TVirtualBranchBrowsable::GetLeaves() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#10 0x00007feb91b1ccb9 in TVirtualBranchBrowsable::IsFolder() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#11 0x00007feb91b9c9cf in TMethodBrowsable::GetIconName() const () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#12 0x00007feb78d596d7 in TGFileBrowser::GetObjPicture(TGPicture const**, TObject*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#13 0x00007feb78d5b1cd in TGFileBrowser::Add(TObject*, char const*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#14 0x00007feba0d3c9e2 in TBrowser::Add(TObject*, char const*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#15 0x00007feba0dbc04f in TCollection::Browse(TBrowser*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libCore.so
#16 0x00007feb91b343e9 in TBranchElement::Browse(TBrowser*) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libTree.so
#17 0x00007feb78d5c4dd in TGFileBrowser::DoubleClicked(TGListTreeItem*, int) () from /opt/cms/slc6_amd64_gcc493/lcg/root/6.02.12-kpegke5/lib/libGui.so
#18 0x00007feb9d4b6b27 in ?? ()
#19 0x0000000000000000 in ?? ()
===========================================================

```

**Comment by katilp** [comment]
Plain root part removed from the instructions https://github.com/cernopendata/opendata.cern.ch/pull/3171 and https://github.com/cernopendata/opendata.cern.ch/pull/3170 - closing
