### ISSUE TITLE
Changes needed for mkedanlzr to work

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#114]
From https://github.com/cernopendata/opendata.cern.ch/issues/3165

To show basic analysis in getting started, it would be best to start with `mkedanlzr MiniAnalyzer` as instructed in https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2015#Skeleton_for_CMSSW_Analysis

In the CMSSW_7_6_7 release, this results in an error:

```
 $ mkedanlzr MiniAnalyzer
Traceback (most recent call last):
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/bin/slc6_amd64_gcc493/mkedanlzr", line 53, in <module>
    generate(config('EDAnalyzer', pkg_help(), tmpl_dir()))
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/cms.py", line 122, in generate
    obj = code_generator(config)
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/utils.py", line 124, in code_generator
    obj = getattr(module, klass)(kwds)
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/pkg.py", line 48, in __init__
    self.author = user_info(self.config.get('author', None))
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/utils.py", line 100, in user_info
    pwdstr = pwd.getpwnam(os.getlogin())
OSError: [Errno 2] No such file or directory
```

Or if run with the  author input field (see mkedanlz):

```
[12:13:42] cmsusr@2d9cc9ce0d48 ~/CMSSW_7_6_7/src/Test $ less /opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/bin/slc6_amd64_gcc493/mkedanlzr
[12:14:18] cmsusr@2d9cc9ce0d48 ~/CMSSW_7_6_7/src/Test $ mkedanlzr MiniAnalyzer -author "Kati L"
Traceback (most recent call last):
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/bin/slc6_amd64_gcc493/mkedanlzr", line 53, in <module>
    generate(config('EDAnalyzer', pkg_help(), tmpl_dir()))
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/cms.py", line 123, in generate
    obj.generate()
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/pkg.py", line 168, in generate
    kwds = self.get_kwds()
  File "/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/pkg.py", line 146, in get_kwds
    '__user__': os.getlogin(),
OSError: [Errno 2] No such file or directory
```

This can be fixed by adding `import pwd` to `/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/pkg.py` (sudo needed) and replacing the line 147 (was 146):
`
    '__user__': os.getlogin(),
`
with
`
  '__user__': pwd.getpwuid(os.geteuid())[0],`

If the same substitution is done also in `/opt/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_7/python/FWCore/Skeletons/utils.py
`, the author flag is not needed.

**Comment by katilp** [comment]
@tpmccauley Could we possibly have these changes in the container image already?

**Comment by katilp** [comment]
OK, that's fine. It works indeed out of the box in CMSSW_5_3_32. I do not think that we need to propose using any release between that and CMSSW_7_6_7 for OD users. 

I have not checked any more recent releases, nor on lxplus. If it fails there, it would make sense to fix it in the CMSSW release for the future.

**Comment by tpmccauley** [comment]
I should have put it a better way: no fix is needed for releases before CMSSW_6_2_X :)

**Comment by katilp** [comment]
It looks that it is working on lxplus for CMSSW_10 so hopefully no fixes are needed for releases later than CMSSW_7_6_7 (unless this is something container-specific)

**Comment by tpmccauley** [comment]
It does not work for CMSSW_10_6_4 for example, using
```
docker run -it gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_4-slc7_amd64_gcc700 /bin/bash
```

**Comment by tpmccauley** [comment]
When/if [!46](https://gitlab.cern.ch/cms-cloud/cmssw-docker/-/merge_requests/46) is merged this issue can be closed.

**Comment by katilp** [comment]
OK, thanks. So the difference comes at the OS level,  lxplus vs the container OS. Somehow confusing asI would assume that they should both be from the same base. 

This is probably an edge case, but I wonder if other EDM tools are or will be affected.

**Comment by tpmccauley** [comment]
From CMSSW_11 this is fixed for pkg.py:
https://github.com/cms-sw/cmssw/commit/6f317b655f0b49a0625955beea852c40e85c92c7#diff-a6a3b66526f09250194fb58eac4b0635c95a439d0a4a7f713e92fc38fb59027a

**Comment by tpmccauley** [comment]
It is still used in utils.py:
https://github.com/cms-sw/cmssw/blob/e2e55a4aeb66e4b2e4e636c23f336a741fc03505/FWCore/Skeletons/python/utils.py#L116

**Comment by katilp** [comment]
OK, maybe we should propose a change for `utils.py` as well.

It is not that os would give anything different as such, it is what `getlogin()` gives, and that's different in the container. 
I guess the change should work in lxplus (or other similar places), it is described in https://docs.python.org/3.7/library/os.html#os.getlogin
